//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AulaNeri2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso
    {
        public int curCodigo { get; set; }
        public string curDescricao { get; set; }
        public string curProferror { get; set; }
        public Nullable<float> curPreco { get; set; }
    }
}
